=== bjbm94/Actividad-7-3/Drones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="drones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dron">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modelo">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="tipo">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="AÃ©reo"/>
                                                        <xs:enumeration value="Terrestre"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="metodo_de_vuelo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Control remoto"/>
                                        <xs:enumeration value="Control por tablet/smartphone"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="video" type="xs:string" />
                            <xs:element name="fotografia" type="xs:string" />
                            <xs:element name="dimensiones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="plegado" type="xs:string" />
                                        <xs:element name="desplegado" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="peso" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="caracteristicas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="conectividad" type="xs:string" />
                                        <xs:element name="potencia_bateria" type="xs:string" />
                                        <xs:element name="autonomia_de_vuelo" type="xs:string" />
                                        <xs:element name="alcance" type="xs:string" />
                                        <xs:element name="sistemas_operativos" type="xs:string" maxOccurs="4" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="imagen_de_dron" type="xs:string" />
                            <xs:element name="precio" type="xs:string" />
                            <xs:element name="url" type="xs:string" />
                            <xs:element name="comentarios" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bjbm94/Actividad-7-3/Drones.xml
<?xml version="1.0" encoding="UTF-8"?>
<drones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Drones.xsd">
    <dron>
        <modelo tipo="Aéreo">DJI Mavic 2 Zoom</modelo>
        <metodo_de_vuelo>Control remoto</metodo_de_vuelo>
        <video>Sí</video>
        <fotografia>Sí</fotografia>
        <dimensiones peso="905g">
            <plegado>214×91×84 mm (largo × ancho × alto)</plegado>
            <desplegado>322×242×84 mm (largo × ancho × alto)</desplegado>
        </dimensiones>
        <caracteristicas>
            <conectividad>Sí</conectividad>
            <potencia_bateria>80 W</potencia_bateria>
            <autonomia_de_vuelo>31 min</autonomia_de_vuelo>
            <alcance>8000 m</alcance>
            <sistemas_operativos>IOS 9.0 o posterior</sistemas_operativos>
            <sistemas_operativos>Android 5.0 o posterior</sistemas_operativos>
        </caracteristicas>
        <imagen_de_dron>dron.jpg</imagen_de_dron>
        <precio>1099,00 €</precio>
        <url>https://visanta.com/drones/13957-drone-dji-mavic-2-zoom-6958265174452.html?search_query=dji%20&amp;fast_search=fs</url>
        <comentarios>Una compra recomendada para quien se inicia o viene de otro dron de una gama más baja(Por ejemplo como un Mavic Air).</comentarios>
    </dron>
</drones>
